### ISSUE TITLE
Lots of WARNINGs when building jphyloref

### ISSUE THREAD

**Issue by iimog** [phyloref/jphyloref#82] opened 2021-06-17 12:55 UTC
When building `jphyloref` with `mvn package` (and properly setting `JAVA_HOME` #81) there are lots of warnings about "overlapping classes". These are just warnings and building still works but there are so many of them that it is hard to see other build log messages that might be more relevant. In total, 727 of 928 lines in the build log are warnings. Is there a way to suppress (or better avoid) these overlapping class warnings?

**Comment by gaurav** [comment] 2021-06-17 21:28
Fixed in bbf672c911a -- turns out this was caused by a couple of inefficient imports and an oddity with the way shaded JARs work. Could you please recheck this with the `improvements-from-joss-review` branch (PR #84)? I'm going to leave that PR open for a bit in case you or our other reviewer have additional issues that need fixing.

**Comment by iimog** [comment] 2021-06-18 12:05
Awesome, can confirm that these WARNINGs are gone in the `improvements-from-joss-review` branch.

**Closed** 2021-07-07 19:07 UTC
